name: Deploy Azure Resources and Function

on:
  push:
    branches:
      - main

jobs:
  Continuous-Training:
    runs-on: ubuntu-latest

    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      TENANT_ID: ${{ secrets.TENANT_ID }}
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
      AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
      LOCATION: ${{ secrets.LOCATION }}
      AML_WORKSPACE: ${{ secrets.AML_WORKSPACE }}
      AZURE_STORAGE_CONTAINER_NAME: ${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}
      AZURE_STORAGE_BLOB_NAME: ${{ secrets.AZURE_STORAGE_BLOB_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Install requirements
        run: sudo apt-get update

      - name: Install Python dependencies
        run: make install

      - name: Login with service principal
        run: make login

      # -----------------------------------------------------
      #               PREPARE STEP
      # -----------------------------------------------------

      - name: Run Prepare Step
        id: prepare
        run: |
          python src/data/prepare_data.py
  

      # -----------------------------------------------------
      #               PREPROCESS STEP
      # -----------------------------------------------------
      - name: Run Preprocess Step
        id: preprocess
        run: |
          python src/data/preprocess.py


      # -----------------------------------------------------
      #               COMPUTE & TRAINING STEP
      # -----------------------------------------------------
      - name: Create Compute Cluster
        run: |
          az ml compute create --name cpu-cluster --type amlcompute --min-instances 0 --max-instances 4 --size Standard_D2_v2 --resource-group $RESOURCE_GROUP --workspace-name $AML_WORKSPACE
      
      - name: Train on Azure ML
        run: |
          JOB_NAME=$(az ml job create --file .azureml/aml-job.yaml --resource-group $RESOURCE_GROUP --workspace-name $AML_WORKSPACE)

          STATUS=$(az ml job show --name $JOB_NAME --resource-group $RESOURCE_GROUP --workspace-name $AML_WORKSPACE --query status -o tsv)
          echo "Initial status: $STATUS"

          while [[ "$STATUS" != "Completed" && "$STATUS" != "Failed" && "$STATUS" != "Canceled" ]]; do
              echo "Waiting for job to finish... Current status: $STATUS"
              sleep 30  # check every 30 seconds
              STATUS=$(az ml job show --name $JOB_NAME --resource-group $RESOURCE_GROUP --workspace-name $AML_WORKSPACE --query status -o tsv)
          done

          echo "Job finished with status: $STATUS"

          if [[ "$STATUS" != "Completed" ]]; then
            echo "Job did not complete successfully"
            exit 1
          fi
      - name: Delete Compute
        run: |
          az ml compute delete \
            --name cpu-cluster \
            --resource-group $RESOURCE_GROUP \
            --workspace-name $AML_WORKSPACE \
            --yes

            
