name: Deploy Azure Resources and Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      TENANT_ID: ${{ secrets.TENANT_ID }}
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
      AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
      LOCATION: ${{ secrets.LOCATION }}
      AML_WORKSPACE: ${{ secrets.AML_WORKSPACE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Install requirements
        run: sudo apt-get update

      - name: Install Python dependencies
        run: make install

      - name: Login with service principal
        run: make login

      # -----------------------------------------------------
      #               PREPARE STEP
      # -----------------------------------------------------

      - name: Run Prepare Step
        id: prepare
        run: |
          python src/data/prepare_data.py
  

      # -----------------------------------------------------
      #               PREPROCESS STEP
      # -----------------------------------------------------
      - name: Run Preprocess Step
        id: preprocess
        run: |
          python src/data/preprocess.py